import { MOCK_EPOCH } from "@/lib/mock-data";
import { motion } from "framer-motion";
import { Activity, Target, Clock, Info } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

export function GlobalStatusBoard() {
  const { name, description, progress, target, current, deadline, status, id } = MOCK_EPOCH;

  const statusColor = 
    status === 'nominal' ? 'text-green-500' :
    status === 'degraded' ? 'text-yellow-500' :
    'text-red-500';

  return (
    <div className="border border-border bg-card mb-8 relative overflow-hidden group">
      {/* Background Grid Pattern */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:14px_14px] pointer-events-none" />
      
      <div className="p-6 relative z-10">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <span className="text-xs font-bold bg-primary text-primary-foreground px-2 py-0.5 uppercase tracking-widest">
                Current Operation
              </span>
              <span className="text-xs font-mono text-muted-foreground">
                ID: {id}
              </span>
            </div>
            <h2 className="text-2xl md:text-3xl font-bold uppercase tracking-tighter mt-2">
              {name}
            </h2>
            <p className="text-sm text-muted-foreground max-w-xl mt-1">
              {description}
            </p>
          </div>

          <div className="flex items-center gap-6 text-right">
            <div>
              <div className="text-[10px] uppercase text-muted-foreground font-bold tracking-widest mb-1 flex items-center justify-end gap-1">
                System Status
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Info className="w-3 h-3 text-muted-foreground hover:text-foreground cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent side="top">
                    <p className="max-w-[200px] text-xs">Current operational state of the primary network. Degraded states may affect task availability.</p>
                  </TooltipContent>
                </Tooltip>
              </div>
              <div className={`flex items-center justify-end gap-2 font-mono font-bold ${statusColor} uppercase`}>
                <Activity className="w-4 h-4" />
                {status}
              </div>
            </div>
            <div className="hidden md:block w-px h-10 bg-border" />
            <div>
               <div className="text-[10px] uppercase text-muted-foreground font-bold tracking-widest mb-1 flex items-center justify-end gap-1">
                 Deadline
                 <Tooltip>
                  <TooltipTrigger asChild>
                    <Info className="w-3 h-3 text-muted-foreground hover:text-foreground cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent side="top">
                    <p className="max-w-[200px] text-xs">Time remaining before the current epoch ends and motivation scores are finalized.</p>
                  </TooltipContent>
                </Tooltip>
               </div>
               <div className="flex items-center justify-end gap-2 font-mono font-bold">
                 <Clock className="w-4 h-4" />
                 {deadline}
               </div>
            </div>
          </div>
        </div>

        {/* Progress Section */}
        <div className="space-y-2">
          <div className="flex justify-between text-xs font-mono uppercase">
            <span className="flex items-center gap-2">
              Progress Protocol
              <Tooltip>
                <TooltipTrigger asChild>
                  <Info className="w-3 h-3 text-muted-foreground hover:text-foreground cursor-help" />
                </TooltipTrigger>
                <TooltipContent side="top">
                  <p className="max-w-[250px] text-xs">Total motivation generated by the network towards this epoch's goals.</p>
                </TooltipContent>
              </Tooltip>
            </span>
            <span>{current.toLocaleString()} / {target.toLocaleString()} MOTIVATION</span>
          </div>
          
          <div className="h-4 w-full bg-secondary border border-border relative overflow-hidden">
             <motion.div 
               className="h-full bg-foreground absolute top-0 left-0"
               initial={{ width: 0 }}
               animate={{ width: `${progress}%` }}
               transition={{ duration: 1.5, ease: "circOut" }}
             />
             {/* Striped overlay */}
             <div className="absolute inset-0 bg-[linear-gradient(45deg,transparent_25%,rgba(255,255,255,0.1)_25%,rgba(255,255,255,0.1)_50%,transparent_50%,transparent_75%,rgba(255,255,255,0.1)_75%,rgba(255,255,255,0.1)_100%)] bg-[length:10px_10px]" />
          </div>

          <div className="flex justify-between text-[10px] text-muted-foreground font-mono pt-1">
            <span>Initiated: 2023-10-20</span>
            <span className="flex items-center gap-1">
              <Target className="w-3 h-3" />
              Target Lock: {progress}%
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
